const SUPPORTED_LANGUAGES = ["en", "pl"];

const DEFAULT_LOCALES = {
  en: "en-US",
  pl: "pl-PL",
};

const DICTIONARY = {
  en: {
    "app.kicker": "Nest LifeOS MVP",
    "app.nav.core_modules": "Core modules",
    "app.nav.mobile_modules": "Mobile modules",
    "app.nav.dashboard": "Dashboard",
    "app.nav.planning": "Planning",
    "app.nav.habits": "Habits",
    "app.nav.routines": "Routines",
    "app.nav.calendar": "Calendar",
    "app.nav.journal": "Journal",
    "app.nav.life_areas": "Life Areas",
    "app.nav.insights": "Insights",
    "app.nav.assistant": "Assistant",
    "app.nav.settings": "Settings",
    "app.nav.tasks": "Tasks",
    "app.nav.lists": "Lists",
    "app.nav.targets": "Targets",
    "app.nav.goals": "Goals",
    "app.nav.optional_surfaces": "Optional surfaces",
    "app.quote.daily_intention": "A life well lived is built daily, intentionally.",
    "app.account.welcome_back": "Welcome back,",
    "app.utility.search_assistant": "Search or ask Assistant",
    "app.utility.notifications": "Notifications",
    "app.action.sign_out": "Sign out",
    "app.action.signing_out": "Signing out...",
    "mobile.tab.tasks": "Tasks",
    "mobile.tab.habits": "Habits",
    "mobile.tab.goals": "Goals",
    "mobile.tab.journal": "Journal",
    "mobile.tab.calendar": "Calendar",
    "mobile.tab.insights": "Insights",
    "mobile.tab.settings": "Settings",
    "mobile.module.state.loading": "Loading",
    "mobile.module.state.empty": "Empty",
    "mobile.module.state.error": "Error",
    "mobile.module.state.success": "Success",
    "mobile.module.panel.today": "Your day",
    "mobile.module.panel.quick_actions": "Quick actions",
    "mobile.module.panel.live_snapshot": "Live snapshot",
    "mobile.module.panel.api_status": "API client status",
    "mobile.module.panel.conflict_queue": "Conflict queue",
    "mobile.module.panel.connections": "Connections",
    "mobile.module.panel.integration_health": "Integration health",
    "mobile.module.badge.shared_client": "shared client",
    "mobile.module.badge.clear": "clear",
    "mobile.module.badge.open": "open",
    "mobile.module.empty.conflicts.title": "No open conflicts",
    "mobile.module.empty.conflicts.detail": "Queue is clear for this module.",
    "mobile.module.connection.no_scopes": "No granted scopes detected.",
    "mobile.module.connection.extra_scopes": "Least-privilege warning: extra scopes",
    "mobile.module.connection.missing_scopes": "Missing required scopes",
    "mobile.module.connection.baseline_ok": "Scope set matches least-privilege baseline.",
    "mobile.module.connection.connected_at": "Connected",
    "mobile.module.connection.updated_at": "Updated",
    "mobile.module.connection.expires_at": "Expires",
    "mobile.module.connection.scopes": "Scopes",
    "mobile.module.connection.none": "none",
    "mobile.module.action.accept": "Accept",
    "mobile.module.action.override": "Override",
    "mobile.module.action.connect": "Connect",
    "mobile.module.action.revoke": "Revoke",
    "mobile.module.action.run": "Run",
    "mobile.module.health.summary": "Summary",
    "mobile.module.health.window": "Window",
    "mobile.module.health.failures": "Open failures",
    "mobile.module.health.drop_rate": "Drop rate",
    "mobile.module.health.last_success": "Last success",
    "mobile.module.health.last_failure": "Last failure",
    "mobile.module.health.message": "Health update",
    "mobile.calendar.title": "Calendar",
    "mobile.calendar.subtitle": "Plan events linked to tasks, goals, and routines.",
    "mobile.calendar.quick_action.add_event": "Add event",
    "mobile.calendar.quick_action.force_sync": "Force sync",
    "mobile.calendar.feedback.loading": "Loading calendar events...",
    "mobile.calendar.feedback.ready": "Calendar events are ready.",
    "mobile.calendar.feedback.refreshed": "Calendar events refreshed.",
    "mobile.calendar.feedback.created": "Calendar event created.",
    "mobile.calendar.feedback.editing": "Editing {title}.",
    "mobile.calendar.feedback.edit_canceled": "Event edit canceled.",
    "mobile.calendar.feedback.updated": "Calendar event updated.",
    "mobile.calendar.feedback.deleted": "Calendar event deleted.",
    "mobile.calendar.feedback.form_ready": "Add event form is ready below.",
    "mobile.calendar.feedback.syncing": "Syncing Google Calendar...",
    "mobile.calendar.feedback.sync_completed": "Calendar sync completed.",
    "mobile.calendar.validation.title_required": "Event title is required.",
    "mobile.calendar.validation.datetime_required": "Start and end date-time are required.",
    "mobile.calendar.validation.end_after_start": "End time must be after start time.",
    "mobile.calendar.panel.events": "Calendar events",
    "mobile.calendar.panel.upcoming": "Upcoming events",
    "mobile.calendar.panel.next_event": "Next: {title} at {time}",
    "mobile.calendar.panel.first_event": "Create the first event for your day.",
    "mobile.calendar.action.refresh": "Refresh",
    "mobile.calendar.action.refreshing": "Refreshing...",
    "mobile.calendar.action.create": "Create event",
    "mobile.calendar.action.creating": "Creating...",
    "mobile.calendar.action.save": "Save event",
    "mobile.calendar.action.saving": "Saving...",
    "mobile.calendar.action.cancel": "Cancel",
    "mobile.calendar.action.edit": "Edit",
    "mobile.calendar.action.delete": "Delete",
    "mobile.calendar.action.deleting": "Deleting...",
    "mobile.calendar.empty.events": "No calendar events yet.",
    "mobile.calendar.field.title": "Event title",
    "mobile.calendar.field.description": "Description",
    "mobile.calendar.field.start": "Start YYYY-MM-DDTHH:mm",
    "mobile.calendar.field.end": "End YYYY-MM-DDTHH:mm",
    "mobile.calendar.a11y.refresh": "Refresh calendar events",
    "mobile.calendar.a11y.loading": "Loading calendar events",
    "mobile.calendar.a11y.create": "Create calendar event",
    "mobile.calendar.a11y.edit_title": "Edit title for {title}",
    "mobile.calendar.a11y.edit_description": "Edit description for {title}",
    "mobile.calendar.a11y.edit_start": "Edit start date and time for {title}",
    "mobile.calendar.a11y.edit_end": "Edit end date and time for {title}",
    "mobile.calendar.a11y.save": "Save {title}",
    "mobile.calendar.a11y.cancel_edit": "Cancel editing {title}",
    "mobile.calendar.a11y.edit": "Edit {title}",
    "mobile.calendar.a11y.delete": "Delete {title}",
    "mobile.calendar.alert.delete_title": "Delete event?",
    "mobile.calendar.alert.delete_body": "This calendar event will be removed.",
    "mobile.calendar.connection.connect_outside_v1": "Provider connect is outside the V1 founder-ready scope. Use Nest-first events for now.",
    "mobile.tasks.title": "Tasks + Lists",
    "mobile.tasks.subtitle": "Practical mobile flow for standalone tasks and list structure.",
    "mobile.tasks.loading": "Loading tasks and lists...",
    "mobile.tasks.feedback.ready": "Tasks and lists are ready.",
    "mobile.tasks.feedback.loaded": "Tasks and lists are loaded.",
    "mobile.tasks.feedback.refreshed": "Tasks and lists have been refreshed.",
    "mobile.tasks.feedback.list_created": "List created successfully.",
    "mobile.tasks.feedback.list_updated": "List updated successfully.",
    "mobile.tasks.feedback.list_deleted": "List deleted successfully.",
    "mobile.tasks.feedback.task_created": "Task created successfully.",
    "mobile.tasks.feedback.task_updated": "Task updated successfully.",
    "mobile.tasks.feedback.task_reopened": "Task reopened.",
    "mobile.tasks.feedback.task_completed": "Task completed.",
    "mobile.tasks.feedback.task_deleted": "Task deleted successfully.",
    "mobile.tasks.validation.list_name_required": "List name is required.",
    "mobile.tasks.validation.select_parent_required": "Select parent for selected parent type.",
    "mobile.tasks.validation.task_title_required": "Task title is required.",
    "mobile.tasks.alert.delete_list_title": "Delete list?",
    "mobile.tasks.alert.delete_list_body": "Tasks in this list will lose list assignment.",
    "mobile.tasks.alert.delete_task_title": "Delete task?",
    "mobile.tasks.alert.delete_task_body": "This action cannot be undone.",
    "mobile.tasks.metric.open": "Open: {count}",
    "mobile.tasks.metric.lists": "Lists: {count}",
    "mobile.tasks.focus.title": "Daily focus",
    "mobile.tasks.focus.no_list": "No list",
    "mobile.tasks.fallback.list": "List",
    "mobile.tasks.focus.open_count": "{count} open",
    "mobile.tasks.focus.list_count": "{count} lists",
    "mobile.tasks.focus.fallback_title": "Plan one concrete next step",
    "mobile.tasks.focus.fallback_body": "Create a task below, then Nest will keep the next useful action here.",
    "mobile.tasks.panel.create_list": "Create list",
    "mobile.tasks.panel.create_task": "Create task",
    "mobile.tasks.panel.filters": "Filters",
    "mobile.tasks.panel.no_list_tasks": "No list tasks",
    "mobile.tasks.field.list_name": "List name",
    "mobile.tasks.field.list_color": "#789262",
    "mobile.tasks.field.task_title": "Task title",
    "mobile.tasks.field.search": "Search tasks",
    "mobile.tasks.parent.none": "none",
    "mobile.tasks.parent.goal": "goal",
    "mobile.tasks.parent.target": "target",
    "mobile.tasks.parent.life_area": "life area",
    "mobile.tasks.priority.low": "Low",
    "mobile.tasks.priority.medium": "Medium",
    "mobile.tasks.priority.high": "High",
    "mobile.tasks.priority.urgent": "Urgent",
    "mobile.tasks.status.todo": "To do",
    "mobile.tasks.status.in_progress": "In progress",
    "mobile.tasks.status.done": "Done",
    "mobile.tasks.status.canceled": "Canceled",
    "mobile.tasks.filter.all": "all",
    "mobile.tasks.filter.open": "open",
    "mobile.tasks.filter.done": "done",
    "mobile.tasks.action.refresh": "Refresh",
    "mobile.tasks.action.refreshing": "Refreshing...",
    "mobile.tasks.action.cancel": "Cancel",
    "mobile.tasks.action.delete": "Delete",
    "mobile.tasks.action.create_list": "Create list",
    "mobile.tasks.action.create_task": "Create task",
    "mobile.tasks.action.save_task": "Save task",
    "mobile.tasks.action.save_list": "Save list",
    "mobile.tasks.action.edit": "Edit",
    "mobile.tasks.action.edit_list": "Edit list",
    "mobile.tasks.action.delete_list": "Delete list",
    "mobile.tasks.action.deleting": "Deleting...",
    "mobile.tasks.action.saving": "Saving...",
    "mobile.tasks.action.updating": "Updating...",
    "mobile.tasks.action.mark_done": "Mark done",
    "mobile.tasks.action.review_task": "Review task",
    "mobile.tasks.action.reopen": "Reopen",
    "mobile.tasks.action.done": "Done",
    "mobile.tasks.empty.no_tasks": "No tasks.",
    "mobile.goals.title": "Goals + Targets",
    "mobile.goals.subtitle": "Real mobile planning flow with API-backed goals and measurable checkpoints.",
    "mobile.goals.loading": "Loading goals and targets...",
    "mobile.goals.feedback.ready": "Goals and targets are ready.",
    "mobile.goals.feedback.loaded": "Goals and targets are loaded.",
    "mobile.goals.feedback.refreshed": "Goals and targets have been refreshed.",
    "mobile.goals.feedback.goal_created": "Goal created successfully.",
    "mobile.goals.feedback.goal_updated": "Goal updated successfully.",
    "mobile.goals.feedback.goal_archived": "Goal archived successfully.",
    "mobile.goals.feedback.target_created": "Target created successfully.",
    "mobile.goals.feedback.target_updated": "Target updated successfully.",
    "mobile.goals.feedback.target_archived": "Target archived successfully.",
    "mobile.goals.validation.goal_title_required": "Goal title is required.",
    "mobile.goals.validation.choose_goal": "Choose a goal for the target.",
    "mobile.goals.validation.target_title_required": "Target title is required.",
    "mobile.goals.alert.archive_goal_title": "Archive goal?",
    "mobile.goals.alert.archive_goal_body": "The goal will be archived and removed from the active mobile flow.",
    "mobile.goals.alert.archive_target_title": "Archive target?",
    "mobile.goals.alert.archive_target_body": "The target will be archived and removed from the active mobile flow.",
    "mobile.goals.metric.goals": "Goals: {count}",
    "mobile.goals.metric.active": "Active: {count}",
    "mobile.goals.metric.targets": "Targets: {count}",
    "mobile.goals.panel.create_goal": "Create goal",
    "mobile.goals.panel.create_target": "Create target",
    "mobile.goals.panel.targets": "Targets",
    "mobile.goals.field.goal_title": "Goal title",
    "mobile.goals.field.short_description": "Short description",
    "mobile.goals.field.target_date": "Target date (YYYY-MM-DD)",
    "mobile.goals.field.target_title": "Target title",
    "mobile.goals.field.metric_type": "Metric type (count, percent, steps...)",
    "mobile.goals.field.target_value": "Target value",
    "mobile.goals.field.current_value": "Current value",
    "mobile.goals.field.unit": "Unit",
    "mobile.goals.field.due_date": "Due date",
    "mobile.goals.field.date": "YYYY-MM-DD",
    "mobile.goals.status.active": "Active",
    "mobile.goals.status.paused": "Paused",
    "mobile.goals.status.completed": "Completed",
    "mobile.goals.status.archived": "Archived",
    "mobile.goals.action.refresh": "Refresh",
    "mobile.goals.action.refreshing": "Refreshing...",
    "mobile.goals.action.cancel": "Cancel",
    "mobile.goals.action.archive": "Archive",
    "mobile.goals.action.archiving": "Archiving...",
    "mobile.goals.action.create_goal": "Create goal",
    "mobile.goals.action.create_target": "Create target",
    "mobile.goals.action.edit": "Edit",
    "mobile.goals.action.save_goal": "Save goal",
    "mobile.goals.action.save_target": "Save target",
    "mobile.goals.action.saving": "Saving...",
    "mobile.goals.empty.targets": "No targets yet.",
    "mobile.goals.meta.due": "Due: {date}",
    "mobile.settings.title": "Settings + more",
    "mobile.settings.subtitle": "Reach core mobile settings, sync tools, and the extra surfaces that do not belong in the main daily tab loop.",
    "mobile.settings.metric.language": "Language",
    "mobile.settings.metric.pending_sync_items": "Pending sync items",
    "mobile.settings.metric.auto_sync_on": "Auto sync on",
    "mobile.settings.metric.auto_sync_paused": "Auto sync paused",
    "mobile.settings.metric.manual_sync_available": "manual sync available",
    "mobile.settings.metric.lag": "lag",
    "mobile.settings.panel.core_settings": "Core settings",
    "mobile.settings.panel.core_settings_text": "Open the advanced settings modal for language selection, offline sync, notifications, and Copilot controls.",
    "mobile.settings.panel.open_advanced": "Open advanced settings",
    "mobile.settings.panel.module_access": "Module access",
    "mobile.settings.panel.module_access_text": "Routines and life areas are managed from the mobile habits and journal flows. These shortcuts make that easier to reach.",
    "mobile.settings.panel.additional_surfaces": "Additional surfaces",
    "mobile.settings.panel.additional_surfaces_text": "Keep the main tab bar focused on the daily loop while still exposing the non-core surfaces already available in the app.",
    "mobile.settings.route.habits_routines": "Habits + Routines",
    "mobile.settings.route.journal_life_areas": "Journal + Life Areas",
    "mobile.settings.route.goals_targets": "Goals + Targets",
    "mobile.settings.route.tasks_lists": "Tasks + Lists",
    "public.kicker": "Life management in one calm place",
    "public.nav.welcome": "Welcome",
    "public.nav.sign_in": "Sign in",
    "public.nav.register": "Register",
    "public.footer.runtime": "Web app: http://localhost:9001 | API: http://localhost:9000",
    "auth.title.login": "Sign in to your private workspace",
    "auth.title.register": "Create your Nest account",
    "auth.subtitle": "Sign in or create an account, then finish onboarding before entering your dashboard.",
    "auth.section.language": "Language",
    "auth.section.account": "Account access",
    "auth.section.status": "Status",
    "auth.section.error": "Something went wrong",
    "auth.switch_to_register": "Create account instead",
    "auth.switch_to_login": "Use existing account",
    "auth.field.name": "Name",
    "auth.field.email": "Email",
    "auth.field.password": "Password",
    "auth.field.password_confirm": "Confirm password",
    "auth.action.sign_in": "Sign in",
    "auth.action.signing_in": "Signing in...",
    "auth.action.create_account": "Create account",
    "auth.action.creating_account": "Creating account...",
    "auth.feedback.default": "Sign in to access your private workspace.",
    "auth.feedback.signed_in": "Signed in. Redirecting...",
    "auth.feedback.created": "Account created. Redirecting...",
    "auth.error.password_mismatch": "The password confirmation does not match.",
    "auth.error.login_invalid": "We couldn't sign you in. Check your email and password and try again.",
    "auth.error.login_generic": "We couldn't sign you in right now. Please try again in a moment.",
    "auth.error.register_generic": "We couldn't create your account right now. Please try again in a moment.",
    "auth.language.helper": "Choose the language for sign-in and onboarding. You can change it later in settings.",
    "onboarding.title": "Finish your account setup",
    "onboarding.subtitle": "Choose your display name and language before entering the dashboard.",
    "onboarding.required.display_name": "Required field",
    "onboarding.required.language": "Required field",
    "onboarding.apply_mode": "Applies",
    "onboarding.apply_mode.value": "Immediately",
    "onboarding.panel.title": "Account setup",
    "onboarding.field.display_name": "Display name",
    "onboarding.field.language": "Language",
    "onboarding.action.continue": "Continue",
    "onboarding.feedback.default": "Complete onboarding with your display name and language.",
    "onboarding.feedback.success": "Setup saved. Redirecting to your dashboard...",
    "onboarding.error.generic": "We couldn't save your setup right now. Please try again.",
    "dashboard.error.load": "We couldn't load the dashboard right now",
    "dashboard.greeting.morning": "Good morning",
    "dashboard.greeting.afternoon": "Good afternoon",
    "dashboard.greeting.evening": "Good evening",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "You've got this.",
    "dashboard.hero.title": "Today at a glance",
    "dashboard.hero.summary": "You're making steady progress.",
    "dashboard.hero.progress.showcase": "You're making steady progress.",
    "dashboard.hero.progress.live": "{tasks} completed tasks and {habits} active habits are already supporting the day.",
    "dashboard.metric.tasks_completed": "Tasks completed",
    "dashboard.metric.habits_active": "Active habits",
    "dashboard.metric.mindful_time": "Mindful time",
    "dashboard.metric.focus_score": "Focus score",
    "dashboard.timeline.type.routine": "Routine",
    "dashboard.timeline.type.habit": "Habit",
    "dashboard.timeline.type.focus_block": "Focus block",
    "dashboard.timeline.type.event": "Event",
    "dashboard.timeline.type.life_area": "Life area",
    "dashboard.timeline.type.recovery": "Recovery",
    "dashboard.timeline.now": "Now",
    "dashboard.timeline.morning_routine": "Morning routine",
    "dashboard.timeline.workout": "Workout",
    "dashboard.timeline.deep_work": "Deep work block",
    "dashboard.timeline.team_sync": "Team sync",
    "dashboard.timeline.product_workshop": "Prepare for product strategy workshop",
    "dashboard.timeline.family_time": "Family time",
    "dashboard.timeline.dinner_unwind": "Dinner and unwind",
    "dashboard.timeline.reflect_plan": "Reflect and plan",
    "dashboard.timeline.sleep": "Sleep",
    "dashboard.list.note.high_impact": "High impact",
    "dashboard.list.note.work": "Work",
    "dashboard.list.note.finance": "Finance",
    "dashboard.list.note.personal": "Personal",
    "dashboard.badge.today": "Today",
    "dashboard.badge.tomorrow": "Tomorrow",
    "dashboard.badge.open": "Open",
    "dashboard.habit.streak_days": "{count} days",
    "dashboard.reflection.fallback_title": "Evening reflection",
    "dashboard.reflection.fallback_body": "Today felt productive and meaningful. I made progress on what matters most and showed up for myself and others. Grateful for the small wins and the clarity that's coming.",
    "dashboard.reflection.prompt": "How was your day?",
    "dashboard.quick_add.task": "Task",
    "dashboard.quick_add.habit": "Habit",
    "dashboard.quick_add.event": "Event",
    "dashboard.quick_add.note": "Note",
    "dashboard.focus.kicker": "Now focus",
    "dashboard.focus.default_title": "Prepare for product strategy workshop",
    "dashboard.focus.showcase_detail": "This moves your project forward and aligns the team. A focused block now creates momentum for the week.",
    "dashboard.focus.live_detail": "This move is already alive in the day. Giving it clean attention now will create momentum for everything after it.",
    "dashboard.focus.cta": "Start focus session",
    "dashboard.focus.why": "Why this?",
    "dashboard.focus.meta.impact": "Impact",
    "dashboard.focus.meta.duration": "Duration",
    "dashboard.focus.meta.high_impact": "High impact",
    "dashboard.focus.meta.showcase_duration": "45 min",
    "dashboard.focus.meta.live_duration": "35 min",
    "dashboard.panel.now": "Now",
    "dashboard.panel.dayflow": "Morning / Now / Evening",
    "dashboard.panel.tasks": "Tasks",
    "dashboard.panel.habits": "Habits",
    "dashboard.panel.view_all": "View all",
    "dashboard.panel.view_all_tasks": "View all tasks",
    "dashboard.panel.add_task": "Add task",
    "dashboard.panel.view_full_calendar": "View full calendar",
    "dashboard.insight.title": "Insight of the day",
    "dashboard.insight.quote": "Clarity comes from slowing down long enough to hear what matters.",
    "dashboard.insight.cta": "Explore insights",
    "automations.title": "Automations",
    "automations.subtitle": "Create trigger-based workflows and control active or paused execution.",
    "automations.loading": "Loading your automation rules and recent runs...",
    "automations.ready": "Automation rules and recent runs are ready.",
    "automations.error.load": "We couldn't load automations right now.",
    "automations.created": "Automation rule created and the workspace has been refreshed.",
    "automations.error.create": "We couldn't create that automation rule.",
    "automations.error.filter": "We couldn't refresh runs for that filter.",
    "automations.metric.rules": "Rules",
    "automations.metric.active": "Active",
    "automations.metric.runs": "Runs",
    "automations.panel.builder": "Builder",
    "automations.panel.rule_control": "Rule control",
    "automations.panel.recent_runs": "Recent runs",
    "automations.panel.run_debug": "Run debug",
    "automations.panel.api_status": "Automation API status",
    "automations.builder.callout": "Create a basic automation and run it manually for verification.",
    "automations.field.rule_name": "Rule name",
    "automations.field.action_type": "Action type",
    "automations.action.create": "Create rule",
    "automations.action.creating": "Creating...",
    "automations.action.pause": "Pause",
    "automations.action.activate": "Activate",
    "automations.action.run": "Run",
    "automations.action.inspect": "Inspect",
    "automations.action.replay": "Replay",
    "automations.filter.run_status": "Run status filter",
    "automations.filter.all": "all",
    "automations.filter.success": "success",
    "automations.filter.failed": "failed",
    "automations.filter.skipped": "skipped",
    "automations.run.rule": "Rule",
    "automations.run.error": "Error",
    "automations.debug.empty": "Choose a run with Inspect to view action trace and errors.",
    "automations.debug.selected": "Selected run",
    "billing.title": "Billing",
    "billing.subtitle": "Run self-serve checkout and portal flows while monitoring automated recovery.",
    "billing.loading": "Loading billing status, recovery activity, and self-serve sessions...",
    "billing.ready": "Billing status and recovery activity are up to date.",
    "billing.error.load": "We couldn't load billing details right now.",
    "billing.action.completed": "Billing action completed and the latest status has been refreshed.",
    "billing.error.action": "We couldn't complete that billing action.",
    "billing.metric.status": "Status",
    "billing.metric.plan": "Plan",
    "billing.metric.events": "Events",
    "billing.metric.dunning": "Dunning",
    "billing.metric.reconciled": "Reconciled",
    "billing.panel.self_serve": "Self-serve actions",
    "billing.panel.lifecycle": "Lifecycle controls",
    "billing.panel.sessions": "Recent sessions",
    "billing.panel.dunning": "Dunning attempts",
    "billing.panel.events": "Billing events",
    "billing.panel.status": "Billing API status",
    "billing.panel.audit": "Audit reconciliation",
    "billing.self_serve.callout": "Checkout and portal sessions are generated on demand and logged in tenant billing events.",
    "billing.action.checkout": "Create checkout session",
    "billing.action.checkout_busy": "Opening...",
    "billing.action.portal": "Create portal session",
    "billing.action.portal_busy": "Opening...",
    "billing.action.recover": "Recover past due",
    "billing.action.recover_busy": "Recovering...",
    "billing.action.trial": "Start trial (plus)",
    "billing.action.trial_busy": "Starting...",
    "billing.action.activate": "Activate",
    "billing.action.activate_busy": "Activating...",
    "billing.action.past_due": "Mark past due",
    "billing.action.past_due_busy": "Marking...",
    "billing.action.cancel": "Cancel",
    "billing.action.cancel_busy": "Canceling...",
    "billing.empty.sessions.title": "No local session actions yet",
    "billing.empty.sessions.body": "Run checkout or portal action to create self-serve session records.",
    "billing.empty.dunning.title": "No dunning attempts",
    "billing.empty.dunning.body": "Attempts appear when past-due subscriptions are processed.",
    "billing.empty.badge": "empty",
    "billing.clear.badge": "clear",
    "billing.reconciled.yes": "yes",
    "billing.reconciled.no": "no",
    "billing.audit.reconciled": "reconciled",
    "billing.audit.needs_review": "needs review",
    "billing.audit.expected_status": "Expected status event",
    "billing.audit.present": "Present",
    "billing.audit.dunning_without_event": "Dunning attempts without event link",
    "insights.title": "Insights",
    "insights.subtitle": "Track life-area balance and weekly behavioral trends across core modules.",
    "insights.loading": "Loading your balance view, activity trends, and latest briefing...",
    "insights.refreshing": "Refreshing your latest insights...",
    "insights.ready": "Insights are ready.",
    "insights.error.refresh": "We couldn't refresh insights right now.",
    "insights.error.fallback_suffix": "Showing your fallback snapshot instead.",
    "insights.metric.balance_score": "Balance score",
    "insights.metric.window": "Window",
    "insights.metric.trend_events": "Trend events",
    "insights.metric.retention": "7d retention",
    "insights.metric.days": "days",
    "insights.panel.status": "API status",
    "insights.panel.balance": "Life-area balance",
    "insights.panel.trends": "Weekly trends (6 buckets)",
    "insights.panel.growth": "Growth loops dashboard",
    "insights.panel.briefing": "AI briefing",
    "insights.action.refresh": "Refresh trends",
    "insights.action.refreshing": "Refreshing...",
    "insights.action.export": "Export snapshot",
    "insights.balance.target_vs_actual": "Target {target}% vs actual {actual}%",
    "insights.trend.total": "Total events in selected range",
    "insights.growth.funnel": "Funnel",
    "insights.growth.signups": "signups",
    "insights.growth.onboarding": "onboarding complete",
    "insights.growth.trials": "trials",
    "insights.growth.activations": "activations",
    "insights.growth.retention": "Retention",
    "insights.growth.retained_users": "retained users",
    "insights.growth.monetization": "Monetization",
    "insights.growth.active_subscriptions": "active subscriptions",
    "insights.growth.weekly_action": "Weekly action",
    "insights.growth.empty": "Growth dashboard is not available right now. Your core insights view is still available.",
    "insights.briefing.empty": "No briefing is ready yet. Once one is generated, it will appear here.",
  },
  pl: {
    "app.kicker": "Nest LifeOS MVP",
    "app.nav.core_modules": "Glowne moduly",
    "app.nav.mobile_modules": "Moduly mobilne",
    "app.nav.dashboard": "Dashboard",
    "app.nav.planning": "Planowanie",
    "app.nav.habits": "Nawyki",
    "app.nav.routines": "Rutyny",
    "app.nav.calendar": "Kalendarz",
    "app.nav.journal": "Dziennik",
    "app.nav.life_areas": "Obszary zycia",
    "app.nav.insights": "Wnioski",
    "app.nav.assistant": "Asystent",
    "app.nav.settings": "Ustawienia",
    "app.nav.tasks": "Zadania",
    "app.nav.lists": "Listy",
    "app.nav.targets": "Targety",
    "app.nav.goals": "Cele",
    "app.nav.optional_surfaces": "Powierzchnie opcjonalne",
    "app.quote.daily_intention": "Dobrze przezyte zycie buduje sie codziennie, intencjonalnie.",
    "app.account.welcome_back": "Milo cie znow widziec,",
    "app.utility.search_assistant": "Szukaj lub zapytaj Asystenta",
    "app.utility.notifications": "Powiadomienia",
    "app.action.sign_out": "Wyloguj sie",
    "app.action.signing_out": "Wylogowywanie...",
    "mobile.tab.tasks": "Zadania",
    "mobile.tab.habits": "Nawyki",
    "mobile.tab.goals": "Cele",
    "mobile.tab.journal": "Dziennik",
    "mobile.tab.calendar": "Kalendarz",
    "mobile.tab.insights": "Wnioski",
    "mobile.tab.settings": "Ustawienia",
    "mobile.module.state.loading": "Ladowanie",
    "mobile.module.state.empty": "Pusto",
    "mobile.module.state.error": "Blad",
    "mobile.module.state.success": "Gotowe",
    "mobile.module.panel.today": "Twoj dzien",
    "mobile.module.panel.quick_actions": "Szybkie akcje",
    "mobile.module.panel.live_snapshot": "Biezacy obraz",
    "mobile.module.panel.api_status": "Status klienta API",
    "mobile.module.panel.conflict_queue": "Kolejka konfliktow",
    "mobile.module.panel.connections": "Polaczenia",
    "mobile.module.panel.integration_health": "Zdrowie integracji",
    "mobile.module.badge.shared_client": "wspolny klient",
    "mobile.module.badge.clear": "czysto",
    "mobile.module.badge.open": "otwarte",
    "mobile.module.empty.conflicts.title": "Brak otwartych konfliktow",
    "mobile.module.empty.conflicts.detail": "Kolejka jest czysta dla tego modulu.",
    "mobile.module.connection.no_scopes": "Nie wykryto przyznanych zakresow.",
    "mobile.module.connection.extra_scopes": "Ostrzezenie least-privilege: dodatkowe zakresy",
    "mobile.module.connection.missing_scopes": "Brakuje wymaganych zakresow",
    "mobile.module.connection.baseline_ok": "Zestaw zakresow zgadza sie z minimalnym baseline.",
    "mobile.module.connection.connected_at": "Polaczono",
    "mobile.module.connection.updated_at": "Zaktualizowano",
    "mobile.module.connection.expires_at": "Wygasa",
    "mobile.module.connection.scopes": "Zakresy",
    "mobile.module.connection.none": "brak",
    "mobile.module.action.accept": "Akceptuj",
    "mobile.module.action.override": "Zastap",
    "mobile.module.action.connect": "Polacz",
    "mobile.module.action.revoke": "Cofnij",
    "mobile.module.action.run": "Uruchom",
    "mobile.module.health.summary": "Podsumowanie",
    "mobile.module.health.window": "Okno",
    "mobile.module.health.failures": "Otwarte bledy",
    "mobile.module.health.drop_rate": "Wspolczynnik odrzucen",
    "mobile.module.health.last_success": "Ostatni sukces",
    "mobile.module.health.last_failure": "Ostatnia porazka",
    "mobile.module.health.message": "Aktualizacja zdrowia",
    "mobile.calendar.title": "Kalendarz",
    "mobile.calendar.subtitle": "Planuj wydarzenia powiazane z zadaniami, celami i rutynami.",
    "mobile.calendar.quick_action.add_event": "Dodaj wydarzenie",
    "mobile.calendar.quick_action.force_sync": "Wymus synchronizacje",
    "mobile.calendar.feedback.loading": "Laduje wydarzenia kalendarza...",
    "mobile.calendar.feedback.ready": "Wydarzenia kalendarza sa gotowe.",
    "mobile.calendar.feedback.refreshed": "Wydarzenia kalendarza odswiezone.",
    "mobile.calendar.feedback.created": "Wydarzenie kalendarza utworzone.",
    "mobile.calendar.feedback.editing": "Edytujesz {title}.",
    "mobile.calendar.feedback.edit_canceled": "Edycja wydarzenia anulowana.",
    "mobile.calendar.feedback.updated": "Wydarzenie kalendarza zaktualizowane.",
    "mobile.calendar.feedback.deleted": "Wydarzenie kalendarza usuniete.",
    "mobile.calendar.feedback.form_ready": "Formularz dodawania wydarzenia jest gotowy ponizej.",
    "mobile.calendar.feedback.syncing": "Synchronizuje Google Calendar...",
    "mobile.calendar.feedback.sync_completed": "Synchronizacja kalendarza zakonczona.",
    "mobile.calendar.validation.title_required": "Tytul wydarzenia jest wymagany.",
    "mobile.calendar.validation.datetime_required": "Data i czas rozpoczecia oraz zakonczenia sa wymagane.",
    "mobile.calendar.validation.end_after_start": "Czas zakonczenia musi byc po czasie rozpoczecia.",
    "mobile.calendar.panel.events": "Wydarzenia kalendarza",
    "mobile.calendar.panel.upcoming": "Nadchodzace wydarzenia",
    "mobile.calendar.panel.next_event": "Nastepne: {title} o {time}",
    "mobile.calendar.panel.first_event": "Utworz pierwsze wydarzenie dnia.",
    "mobile.calendar.action.refresh": "Odswiez",
    "mobile.calendar.action.refreshing": "Odswiezanie...",
    "mobile.calendar.action.create": "Utworz wydarzenie",
    "mobile.calendar.action.creating": "Tworzenie...",
    "mobile.calendar.action.save": "Zapisz wydarzenie",
    "mobile.calendar.action.saving": "Zapisywanie...",
    "mobile.calendar.action.cancel": "Anuluj",
    "mobile.calendar.action.edit": "Edytuj",
    "mobile.calendar.action.delete": "Usun",
    "mobile.calendar.action.deleting": "Usuwanie...",
    "mobile.calendar.empty.events": "Brak wydarzen kalendarza.",
    "mobile.calendar.field.title": "Tytul wydarzenia",
    "mobile.calendar.field.description": "Opis",
    "mobile.calendar.field.start": "Start YYYY-MM-DDTHH:mm",
    "mobile.calendar.field.end": "Koniec YYYY-MM-DDTHH:mm",
    "mobile.calendar.a11y.refresh": "Odswiez wydarzenia kalendarza",
    "mobile.calendar.a11y.loading": "Ladowanie wydarzen kalendarza",
    "mobile.calendar.a11y.create": "Utworz wydarzenie kalendarza",
    "mobile.calendar.a11y.edit_title": "Edytuj tytul: {title}",
    "mobile.calendar.a11y.edit_description": "Edytuj opis: {title}",
    "mobile.calendar.a11y.edit_start": "Edytuj date i czas rozpoczecia: {title}",
    "mobile.calendar.a11y.edit_end": "Edytuj date i czas zakonczenia: {title}",
    "mobile.calendar.a11y.save": "Zapisz {title}",
    "mobile.calendar.a11y.cancel_edit": "Anuluj edycje {title}",
    "mobile.calendar.a11y.edit": "Edytuj {title}",
    "mobile.calendar.a11y.delete": "Usun {title}",
    "mobile.calendar.alert.delete_title": "Usunac wydarzenie?",
    "mobile.calendar.alert.delete_body": "To wydarzenie kalendarza zostanie usuniete.",
    "mobile.calendar.connection.connect_outside_v1": "Laczenie providerow jest poza zakresem V1 founder-ready. Na razie uzywaj wydarzen tworzonych w Nest.",
    "mobile.tasks.title": "Zadania + Listy",
    "mobile.tasks.subtitle": "Praktyczny mobilny przeplyw dla pojedynczych zadan i struktury list.",
    "mobile.tasks.loading": "Laduje zadania i listy...",
    "mobile.tasks.feedback.ready": "Zadania i listy sa gotowe.",
    "mobile.tasks.feedback.loaded": "Zadania i listy zaladowane.",
    "mobile.tasks.feedback.refreshed": "Zadania i listy zostaly odswiezone.",
    "mobile.tasks.feedback.list_created": "Lista utworzona.",
    "mobile.tasks.feedback.list_updated": "Lista zaktualizowana.",
    "mobile.tasks.feedback.list_deleted": "Lista usunieta.",
    "mobile.tasks.feedback.task_created": "Zadanie utworzone.",
    "mobile.tasks.feedback.task_updated": "Zadanie zaktualizowane.",
    "mobile.tasks.feedback.task_reopened": "Zadanie ponownie otwarte.",
    "mobile.tasks.feedback.task_completed": "Zadanie ukonczone.",
    "mobile.tasks.feedback.task_deleted": "Zadanie usuniete.",
    "mobile.tasks.validation.list_name_required": "Nazwa listy jest wymagana.",
    "mobile.tasks.validation.select_parent_required": "Wybierz element nadrzedny dla wybranego typu.",
    "mobile.tasks.validation.task_title_required": "Tytul zadania jest wymagany.",
    "mobile.tasks.alert.delete_list_title": "Usunac liste?",
    "mobile.tasks.alert.delete_list_body": "Zadania z tej listy straca przypisanie do listy.",
    "mobile.tasks.alert.delete_task_title": "Usunac zadanie?",
    "mobile.tasks.alert.delete_task_body": "Tej akcji nie mozna cofnac.",
    "mobile.tasks.metric.open": "Otwarte: {count}",
    "mobile.tasks.metric.lists": "Listy: {count}",
    "mobile.tasks.focus.title": "Priorytet dnia",
    "mobile.tasks.focus.no_list": "Bez listy",
    "mobile.tasks.fallback.list": "Lista",
    "mobile.tasks.focus.open_count": "{count} otwarte",
    "mobile.tasks.focus.list_count": "{count} list",
    "mobile.tasks.focus.fallback_title": "Zaplanuj jeden konkretny nastepny krok",
    "mobile.tasks.focus.fallback_body": "Utworz zadanie ponizej, a Nest utrzyma tu nastepna uzyteczna akcje.",
    "mobile.tasks.panel.create_list": "Utworz liste",
    "mobile.tasks.panel.create_task": "Utworz zadanie",
    "mobile.tasks.panel.filters": "Filtry",
    "mobile.tasks.panel.no_list_tasks": "Zadania bez listy",
    "mobile.tasks.field.list_name": "Nazwa listy",
    "mobile.tasks.field.list_color": "#789262",
    "mobile.tasks.field.task_title": "Tytul zadania",
    "mobile.tasks.field.search": "Szukaj zadan",
    "mobile.tasks.parent.none": "brak",
    "mobile.tasks.parent.goal": "cel",
    "mobile.tasks.parent.target": "target",
    "mobile.tasks.parent.life_area": "obszar zycia",
    "mobile.tasks.priority.low": "Niski",
    "mobile.tasks.priority.medium": "Sredni",
    "mobile.tasks.priority.high": "Wysoki",
    "mobile.tasks.priority.urgent": "Pilny",
    "mobile.tasks.status.todo": "Do zrobienia",
    "mobile.tasks.status.in_progress": "W toku",
    "mobile.tasks.status.done": "Gotowe",
    "mobile.tasks.status.canceled": "Anulowane",
    "mobile.tasks.filter.all": "wszystkie",
    "mobile.tasks.filter.open": "otwarte",
    "mobile.tasks.filter.done": "gotowe",
    "mobile.tasks.action.refresh": "Odswiez",
    "mobile.tasks.action.refreshing": "Odswiezanie...",
    "mobile.tasks.action.cancel": "Anuluj",
    "mobile.tasks.action.delete": "Usun",
    "mobile.tasks.action.create_list": "Utworz liste",
    "mobile.tasks.action.create_task": "Utworz zadanie",
    "mobile.tasks.action.save_task": "Zapisz zadanie",
    "mobile.tasks.action.save_list": "Zapisz liste",
    "mobile.tasks.action.edit": "Edytuj",
    "mobile.tasks.action.edit_list": "Edytuj liste",
    "mobile.tasks.action.delete_list": "Usun liste",
    "mobile.tasks.action.deleting": "Usuwanie...",
    "mobile.tasks.action.saving": "Zapisywanie...",
    "mobile.tasks.action.updating": "Aktualizacja...",
    "mobile.tasks.action.mark_done": "Oznacz jako gotowe",
    "mobile.tasks.action.review_task": "Sprawdz zadanie",
    "mobile.tasks.action.reopen": "Otworz ponownie",
    "mobile.tasks.action.done": "Gotowe",
    "mobile.tasks.empty.no_tasks": "Brak zadan.",
    "mobile.goals.title": "Cele + Targety",
    "mobile.goals.subtitle": "Realny mobilny przeplyw planowania z celami z API i mierzalnymi checkpointami.",
    "mobile.goals.loading": "Laduje cele i targety...",
    "mobile.goals.feedback.ready": "Cele i targety sa gotowe.",
    "mobile.goals.feedback.loaded": "Cele i targety zaladowane.",
    "mobile.goals.feedback.refreshed": "Cele i targety zostaly odswiezone.",
    "mobile.goals.feedback.goal_created": "Cel utworzony.",
    "mobile.goals.feedback.goal_updated": "Cel zaktualizowany.",
    "mobile.goals.feedback.goal_archived": "Cel zarchiwizowany.",
    "mobile.goals.feedback.target_created": "Target utworzony.",
    "mobile.goals.feedback.target_updated": "Target zaktualizowany.",
    "mobile.goals.feedback.target_archived": "Target zarchiwizowany.",
    "mobile.goals.validation.goal_title_required": "Tytul celu jest wymagany.",
    "mobile.goals.validation.choose_goal": "Wybierz cel dla targetu.",
    "mobile.goals.validation.target_title_required": "Tytul targetu jest wymagany.",
    "mobile.goals.alert.archive_goal_title": "Zarchiwizowac cel?",
    "mobile.goals.alert.archive_goal_body": "Cel zostanie zarchiwizowany i usuniety z aktywnego mobilnego przeplywu.",
    "mobile.goals.alert.archive_target_title": "Zarchiwizowac target?",
    "mobile.goals.alert.archive_target_body": "Target zostanie zarchiwizowany i usuniety z aktywnego mobilnego przeplywu.",
    "mobile.goals.metric.goals": "Cele: {count}",
    "mobile.goals.metric.active": "Aktywne: {count}",
    "mobile.goals.metric.targets": "Targety: {count}",
    "mobile.goals.panel.create_goal": "Utworz cel",
    "mobile.goals.panel.create_target": "Utworz target",
    "mobile.goals.panel.targets": "Targety",
    "mobile.goals.field.goal_title": "Tytul celu",
    "mobile.goals.field.short_description": "Krotki opis",
    "mobile.goals.field.target_date": "Data celu (YYYY-MM-DD)",
    "mobile.goals.field.target_title": "Tytul targetu",
    "mobile.goals.field.metric_type": "Typ metryki (count, percent, steps...)",
    "mobile.goals.field.target_value": "Wartosc docelowa",
    "mobile.goals.field.current_value": "Wartosc obecna",
    "mobile.goals.field.unit": "Jednostka",
    "mobile.goals.field.due_date": "Termin",
    "mobile.goals.field.date": "YYYY-MM-DD",
    "mobile.goals.status.active": "Aktywny",
    "mobile.goals.status.paused": "Wstrzymany",
    "mobile.goals.status.completed": "Ukonczony",
    "mobile.goals.status.archived": "Zarchiwizowany",
    "mobile.goals.action.refresh": "Odswiez",
    "mobile.goals.action.refreshing": "Odswiezanie...",
    "mobile.goals.action.cancel": "Anuluj",
    "mobile.goals.action.archive": "Archiwizuj",
    "mobile.goals.action.archiving": "Archiwizacja...",
    "mobile.goals.action.create_goal": "Utworz cel",
    "mobile.goals.action.create_target": "Utworz target",
    "mobile.goals.action.edit": "Edytuj",
    "mobile.goals.action.save_goal": "Zapisz cel",
    "mobile.goals.action.save_target": "Zapisz target",
    "mobile.goals.action.saving": "Zapisywanie...",
    "mobile.goals.empty.targets": "Brak targetow.",
    "mobile.goals.meta.due": "Termin: {date}",
    "mobile.settings.title": "Ustawienia i wiecej",
    "mobile.settings.subtitle": "Dotrzyj do glownych ustawien mobile, narzedzi synchronizacji i dodatkowych powierzchni, ktore nie naleza do glownej dziennej petli zakladek.",
    "mobile.settings.metric.language": "Jezyk",
    "mobile.settings.metric.pending_sync_items": "Oczekujace elementy sync",
    "mobile.settings.metric.auto_sync_on": "Auto sync wlaczony",
    "mobile.settings.metric.auto_sync_paused": "Auto sync wstrzymany",
    "mobile.settings.metric.manual_sync_available": "reczny sync dostepny",
    "mobile.settings.metric.lag": "opoznienie",
    "mobile.settings.panel.core_settings": "Glowne ustawienia",
    "mobile.settings.panel.core_settings_text": "Otworz zaawansowany modal ustawien dla wyboru jezyka, offline sync, powiadomien i sterowania Copilotem.",
    "mobile.settings.panel.open_advanced": "Otworz zaawansowane ustawienia",
    "mobile.settings.panel.module_access": "Dostep do modulow",
    "mobile.settings.panel.module_access_text": "Rutyny i obszary zycia sa zarzadzane z mobilnych przeplywow nawykow i dziennika. Te skroty ulatwiaja dotarcie tam.",
    "mobile.settings.panel.additional_surfaces": "Dodatkowe powierzchnie",
    "mobile.settings.panel.additional_surfaces_text": "Utrzymaj glowny pasek zakladek skupiony na dziennej petli, jednoczesnie udostepniajac powierzchnie niekrytyczne, ktore juz istnieja w aplikacji.",
    "mobile.settings.route.habits_routines": "Nawyki + Rutyny",
    "mobile.settings.route.journal_life_areas": "Dziennik + Obszary zycia",
    "mobile.settings.route.goals_targets": "Cele + Targety",
    "mobile.settings.route.tasks_lists": "Zadania + Listy",
    "public.kicker": "Zarzadzaj zyciem spokojnie, w jednym miejscu",
    "public.nav.welcome": "Start",
    "public.nav.sign_in": "Zaloguj sie",
    "public.nav.register": "Zarejestruj sie",
    "public.footer.runtime": "Web app: http://localhost:9001 | API: http://localhost:9000",
    "auth.title.login": "Zaloguj sie do swojego prywatnego workspace",
    "auth.title.register": "Utworz konto Nest",
    "auth.subtitle": "Zaloguj sie albo zaloz konto, a potem dokonczy onboarding przed wejsciem do dashboardu.",
    "auth.section.language": "Jezyk",
    "auth.section.account": "Dostep do konta",
    "auth.section.status": "Status",
    "auth.section.error": "Cos poszlo nie tak",
    "auth.switch_to_register": "Utworz nowe konto",
    "auth.switch_to_login": "Mam juz konto",
    "auth.field.name": "Imie",
    "auth.field.email": "Email",
    "auth.field.password": "Haslo",
    "auth.field.password_confirm": "Powtorz haslo",
    "auth.action.sign_in": "Zaloguj sie",
    "auth.action.signing_in": "Logowanie...",
    "auth.action.create_account": "Utworz konto",
    "auth.action.creating_account": "Tworzenie konta...",
    "auth.feedback.default": "Zaloguj sie, aby wejsc do swojego prywatnego workspace.",
    "auth.feedback.signed_in": "Zalogowano. Przekierowuje...",
    "auth.feedback.created": "Konto utworzone. Przekierowuje...",
    "auth.error.password_mismatch": "Potwierdzenie hasla nie zgadza sie.",
    "auth.error.login_invalid": "Nie udalo sie zalogowac. Sprawdz email i haslo, a potem sproboj ponownie.",
    "auth.error.login_generic": "Nie udalo sie teraz zalogowac. Sprobuj ponownie za chwile.",
    "auth.error.register_generic": "Nie udalo sie teraz utworzyc konta. Sprobuj ponownie za chwile.",
    "auth.language.helper": "Wybierz jezyk logowania i onboardingu. Pozniej zmienisz go w ustawieniach.",
    "onboarding.title": "Dokoncz konfiguracje konta",
    "onboarding.subtitle": "Ustaw nazwe wyswietlana i jezyk, zanim wejdziesz do dashboardu.",
    "onboarding.required.display_name": "Pole wymagane",
    "onboarding.required.language": "Pole wymagane",
    "onboarding.apply_mode": "Zastosowanie",
    "onboarding.apply_mode.value": "Od razu",
    "onboarding.panel.title": "Konfiguracja konta",
    "onboarding.field.display_name": "Nazwa wyswietlana",
    "onboarding.field.language": "Jezyk",
    "onboarding.action.continue": "Dalej",
    "onboarding.feedback.default": "Dokoncz onboarding, ustawiajac nazwe wyswietlana i jezyk.",
    "onboarding.feedback.success": "Ustawienia zapisane. Przekierowuje do dashboardu...",
    "onboarding.error.generic": "Nie udalo sie zapisac ustawien. Sprobuj ponownie.",
    "dashboard.error.load": "Nie udalo sie teraz zaladowac dashboardu",
    "dashboard.greeting.morning": "Dzien dobry",
    "dashboard.greeting.afternoon": "Dobre popoludnie",
    "dashboard.greeting.evening": "Dobry wieczor",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Dasz rade.",
    "dashboard.hero.title": "Dzien w jednym spojrzeniu",
    "dashboard.hero.summary": "Robisz stabilny postep.",
    "dashboard.hero.progress.showcase": "Robisz stabilny postep.",
    "dashboard.hero.progress.live": "{tasks} ukonczonych zadan i {habits} aktywnych nawykow juz wspiera ten dzien.",
    "dashboard.metric.tasks_completed": "Ukonczone zadania",
    "dashboard.metric.habits_active": "Aktywne nawyki",
    "dashboard.metric.mindful_time": "Uważny czas",
    "dashboard.metric.focus_score": "Skupienie",
    "dashboard.timeline.type.routine": "Rutyna",
    "dashboard.timeline.type.habit": "Nawyk",
    "dashboard.timeline.type.focus_block": "Blok skupienia",
    "dashboard.timeline.type.event": "Wydarzenie",
    "dashboard.timeline.type.life_area": "Obszar zycia",
    "dashboard.timeline.type.recovery": "Regeneracja",
    "dashboard.timeline.now": "Teraz",
    "dashboard.timeline.morning_routine": "Poranna rutyna",
    "dashboard.timeline.workout": "Trening",
    "dashboard.timeline.deep_work": "Blok glebokiej pracy",
    "dashboard.timeline.team_sync": "Synchronizacja zespolu",
    "dashboard.timeline.product_workshop": "Przygotuj warsztat strategii produktu",
    "dashboard.timeline.family_time": "Czas z rodzina",
    "dashboard.timeline.dinner_unwind": "Kolacja i oddech",
    "dashboard.timeline.reflect_plan": "Refleksja i plan",
    "dashboard.timeline.sleep": "Sen",
    "dashboard.list.note.high_impact": "Wysoki wplyw",
    "dashboard.list.note.work": "Praca",
    "dashboard.list.note.finance": "Finanse",
    "dashboard.list.note.personal": "Prywatne",
    "dashboard.badge.today": "Dzis",
    "dashboard.badge.tomorrow": "Jutro",
    "dashboard.badge.open": "Otwarte",
    "dashboard.habit.streak_days": "{count} dni",
    "dashboard.reflection.fallback_title": "Wieczorna refleksja",
    "dashboard.reflection.fallback_body": "To byl produktywny i sensowny dzien. Posunelam to, co najwazniejsze, i pokazalam sie dla siebie oraz innych. Doceniam male wygrane i klarownosc, ktora przychodzi.",
    "dashboard.reflection.prompt": "Jak minal twoj dzien?",
    "dashboard.quick_add.task": "Zadanie",
    "dashboard.quick_add.habit": "Nawyk",
    "dashboard.quick_add.event": "Wydarzenie",
    "dashboard.quick_add.note": "Notatka",
    "dashboard.focus.kicker": "Priorytet teraz",
    "dashboard.focus.default_title": "Przygotuj warsztat strategii produktu",
    "dashboard.focus.showcase_detail": "To popycha projekt do przodu i ustawia zespol. Skupiony blok teraz zbuduje impet na caly tydzien.",
    "dashboard.focus.live_detail": "Ten ruch juz zyje w planie dnia. Czysta uwaga teraz zbuduje impet dla wszystkiego, co dalej.",
    "dashboard.focus.cta": "Zacznij sesje skupienia",
    "dashboard.focus.why": "Dlaczego to?",
    "dashboard.focus.meta.impact": "Wplyw",
    "dashboard.focus.meta.duration": "Czas",
    "dashboard.focus.meta.high_impact": "Wysoki wplyw",
    "dashboard.focus.meta.showcase_duration": "45 min",
    "dashboard.focus.meta.live_duration": "35 min",
    "dashboard.panel.now": "Teraz",
    "dashboard.panel.dayflow": "Rano / Teraz / Wieczor",
    "dashboard.panel.tasks": "Zadania",
    "dashboard.panel.habits": "Nawyki",
    "dashboard.panel.view_all": "Zobacz wszystkie",
    "dashboard.panel.view_all_tasks": "Zobacz wszystkie zadania",
    "dashboard.panel.add_task": "Dodaj zadanie",
    "dashboard.panel.view_full_calendar": "Zobacz pelny kalendarz",
    "dashboard.insight.title": "Wniosek dnia",
    "dashboard.insight.quote": "Klarownosc przychodzi, kiedy zwolnisz na tyle, by uslyszec to, co ma znaczenie.",
    "dashboard.insight.cta": "Otworz wnioski",
    "automations.title": "Automatyzacje",
    "automations.subtitle": "Tworz przeplywy oparte na wyzwalaczach i kontroluj aktywne lub wstrzymane wykonanie.",
    "automations.loading": "Laduje reguly automatyzacji i ostatnie uruchomienia...",
    "automations.ready": "Reguly automatyzacji i ostatnie uruchomienia sa gotowe.",
    "automations.error.load": "Nie mozemy teraz zaladowac automatyzacji.",
    "automations.created": "Regula automatyzacji zostala utworzona, a workspace odswiezony.",
    "automations.error.create": "Nie mozemy utworzyc tej reguly automatyzacji.",
    "automations.error.filter": "Nie mozemy odswiezyc uruchomien dla tego filtra.",
    "automations.metric.rules": "Reguly",
    "automations.metric.active": "Aktywne",
    "automations.metric.runs": "Uruchomienia",
    "automations.panel.builder": "Kreator",
    "automations.panel.rule_control": "Kontrola regul",
    "automations.panel.recent_runs": "Ostatnie uruchomienia",
    "automations.panel.run_debug": "Diagnostyka uruchomienia",
    "automations.panel.api_status": "Status API automatyzacji",
    "automations.builder.callout": "Utworz podstawowa automatyzacje i uruchom ja recznie do weryfikacji.",
    "automations.field.rule_name": "Nazwa reguly",
    "automations.field.action_type": "Typ akcji",
    "automations.action.create": "Utworz regule",
    "automations.action.creating": "Tworzenie...",
    "automations.action.pause": "Wstrzymaj",
    "automations.action.activate": "Aktywuj",
    "automations.action.run": "Uruchom",
    "automations.action.inspect": "Sprawdz",
    "automations.action.replay": "Powtorz",
    "automations.filter.run_status": "Filtr statusu uruchomien",
    "automations.filter.all": "wszystkie",
    "automations.filter.success": "sukces",
    "automations.filter.failed": "nieudane",
    "automations.filter.skipped": "pominiete",
    "automations.run.rule": "Regula",
    "automations.run.error": "Blad",
    "automations.debug.empty": "Wybierz uruchomienie przez Sprawdz, aby zobaczyc slad akcji i bledy.",
    "automations.debug.selected": "Wybrane uruchomienie",
    "billing.title": "Rozliczenia",
    "billing.subtitle": "Uruchamiaj samoobslugowy checkout i portal oraz monitoruj automatyczne odzyskiwanie platnosci.",
    "billing.loading": "Laduje status rozliczen, odzyskiwanie platnosci i sesje samoobslugowe...",
    "billing.ready": "Status rozliczen i odzyskiwania platnosci jest aktualny.",
    "billing.error.load": "Nie mozemy teraz zaladowac szczegolow rozliczen.",
    "billing.action.completed": "Akcja rozliczeniowa zakonczona, a najnowszy status odswiezony.",
    "billing.error.action": "Nie mozemy dokonczyc tej akcji rozliczeniowej.",
    "billing.metric.status": "Status",
    "billing.metric.plan": "Plan",
    "billing.metric.events": "Zdarzenia",
    "billing.metric.dunning": "Windykacja",
    "billing.metric.reconciled": "Uzgodnione",
    "billing.panel.self_serve": "Akcje samoobslugowe",
    "billing.panel.lifecycle": "Kontrola cyklu zycia",
    "billing.panel.sessions": "Ostatnie sesje",
    "billing.panel.dunning": "Proby odzyskania",
    "billing.panel.events": "Zdarzenia rozliczen",
    "billing.panel.status": "Status API rozliczen",
    "billing.panel.audit": "Uzgodnienie audytu",
    "billing.self_serve.callout": "Sesje checkout i portalu sa generowane na zadanie i zapisywane w zdarzeniach rozliczen tenantow.",
    "billing.action.checkout": "Utworz sesje checkout",
    "billing.action.checkout_busy": "Otwieranie...",
    "billing.action.portal": "Utworz sesje portalu",
    "billing.action.portal_busy": "Otwieranie...",
    "billing.action.recover": "Odzyskaj zaleglosc",
    "billing.action.recover_busy": "Odzyskiwanie...",
    "billing.action.trial": "Rozpocznij trial (plus)",
    "billing.action.trial_busy": "Start...",
    "billing.action.activate": "Aktywuj",
    "billing.action.activate_busy": "Aktywacja...",
    "billing.action.past_due": "Oznacz zaleglosc",
    "billing.action.past_due_busy": "Oznaczanie...",
    "billing.action.cancel": "Anuluj",
    "billing.action.cancel_busy": "Anulowanie...",
    "billing.empty.sessions.title": "Brak lokalnych akcji sesji",
    "billing.empty.sessions.body": "Uruchom checkout lub portal, aby utworzyc rekordy sesji samoobslugowych.",
    "billing.empty.dunning.title": "Brak prob odzyskania",
    "billing.empty.dunning.body": "Proby pojawia sie, gdy subskrypcje z zalegloscia zostana przetworzone.",
    "billing.empty.badge": "pusto",
    "billing.clear.badge": "czysto",
    "billing.reconciled.yes": "tak",
    "billing.reconciled.no": "nie",
    "billing.audit.reconciled": "uzgodnione",
    "billing.audit.needs_review": "do sprawdzenia",
    "billing.audit.expected_status": "Oczekiwane zdarzenie statusu",
    "billing.audit.present": "Obecne",
    "billing.audit.dunning_without_event": "Proby odzyskania bez powiazanego zdarzenia",
    "insights.title": "Wnioski",
    "insights.subtitle": "Sledz balans obszarow zycia i tygodniowe trendy zachowan w modulach core.",
    "insights.loading": "Laduje balans, trendy aktywnosci i najnowszy briefing...",
    "insights.refreshing": "Odswiezam najnowsze wnioski...",
    "insights.ready": "Wnioski sa gotowe.",
    "insights.error.refresh": "Nie mozemy teraz odswiezyc wnioskow.",
    "insights.error.fallback_suffix": "Pokazujemy zapasowy snapshot.",
    "insights.metric.balance_score": "Wynik balansu",
    "insights.metric.window": "Okno",
    "insights.metric.trend_events": "Zdarzenia trendow",
    "insights.metric.retention": "Retencja 7d",
    "insights.metric.days": "dni",
    "insights.panel.status": "Status API",
    "insights.panel.balance": "Balans obszarow zycia",
    "insights.panel.trends": "Trendy tygodniowe (6 koszykow)",
    "insights.panel.growth": "Dashboard petli wzrostu",
    "insights.panel.briefing": "Briefing AI",
    "insights.action.refresh": "Odswiez trendy",
    "insights.action.refreshing": "Odswiezanie...",
    "insights.action.export": "Eksportuj snapshot",
    "insights.balance.target_vs_actual": "Cel {target}% vs aktualnie {actual}%",
    "insights.trend.total": "Laczna liczba zdarzen w wybranym zakresie",
    "insights.growth.funnel": "Lejek",
    "insights.growth.signups": "rejestracje",
    "insights.growth.onboarding": "ukonczony onboarding",
    "insights.growth.trials": "triale",
    "insights.growth.activations": "aktywacje",
    "insights.growth.retention": "Retencja",
    "insights.growth.retained_users": "utrzymani uzytkownicy",
    "insights.growth.monetization": "Monetyzacja",
    "insights.growth.active_subscriptions": "aktywne subskrypcje",
    "insights.growth.weekly_action": "Akcja tygodniowa",
    "insights.growth.empty": "Dashboard wzrostu nie jest teraz dostepny. Widok core insights nadal dziala.",
    "insights.briefing.empty": "Briefing nie jest jeszcze gotowy. Gdy powstanie, pojawi sie tutaj.",
  },
};

export function resolveLanguage(value) {
  if (typeof value === "string" && SUPPORTED_LANGUAGES.includes(value)) {
    return value;
  }

  return "en";
}

export function resolveLocale(language, override) {
  if (typeof override === "string" && override.length > 0) {
    return override;
  }

  const safeLanguage = resolveLanguage(language);
  return DEFAULT_LOCALES[safeLanguage];
}

export function translate(key, language, fallback = key) {
  const safeLanguage = resolveLanguage(language);
  return DICTIONARY[safeLanguage]?.[key] ?? DICTIONARY.en?.[key] ?? fallback;
}

export function formatLocalizedDateTime(value, language, localeOverride) {
  const locale = resolveLocale(language, localeOverride);
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "";
  }

  return new Intl.DateTimeFormat(locale, {
    dateStyle: "short",
    timeStyle: "short",
  }).format(date);
}
