const SUPPORTED_LANGUAGES = ["en", "pl"];

const DEFAULT_LOCALES = {
  en: "en-US",
  pl: "pl-PL",
};

const DICTIONARY = {
  en: {
    "app.kicker": "Nest LifeOS MVP",
    "app.nav.core_modules": "Core modules",
    "app.nav.mobile_modules": "Mobile modules",
    "app.nav.dashboard": "Dashboard",
    "app.nav.planning": "Planning",
    "app.nav.habits": "Habits",
    "app.nav.routines": "Routines",
    "app.nav.calendar": "Calendar",
    "app.nav.journal": "Journal",
    "app.nav.life_areas": "Life Areas",
    "app.nav.insights": "Insights",
    "app.nav.assistant": "Assistant",
    "app.nav.settings": "Settings",
    "app.nav.tasks": "Tasks",
    "app.nav.lists": "Lists",
    "app.nav.targets": "Targets",
    "app.nav.goals": "Goals",
    "app.quote.daily_intention": "A life well lived is built daily, intentionally.",
    "app.account.welcome_back": "Welcome back,",
    "app.utility.search_assistant": "Search or ask Assistant",
    "app.utility.notifications": "Notifications",
    "app.action.sign_out": "Sign out",
    "app.action.signing_out": "Signing out...",
    "mobile.tab.tasks": "Tasks",
    "mobile.tab.habits": "Habits",
    "mobile.tab.goals": "Goals",
    "mobile.tab.journal": "Journal",
    "mobile.tab.calendar": "Calendar",
    "mobile.tab.insights": "Insights",
    "mobile.tab.settings": "Settings",
    "mobile.module.state.loading": "Loading",
    "mobile.module.state.empty": "Empty",
    "mobile.module.state.error": "Error",
    "mobile.module.state.success": "Success",
    "mobile.module.panel.today": "Your day",
    "mobile.module.panel.quick_actions": "Quick actions",
    "mobile.module.panel.live_snapshot": "Live snapshot",
    "mobile.module.panel.api_status": "API client status",
    "mobile.module.panel.conflict_queue": "Conflict queue",
    "mobile.module.panel.connections": "Connections",
    "mobile.module.panel.integration_health": "Integration health",
    "mobile.module.badge.shared_client": "shared client",
    "mobile.module.badge.clear": "clear",
    "mobile.module.badge.open": "open",
    "mobile.module.empty.conflicts.title": "No open conflicts",
    "mobile.module.empty.conflicts.detail": "Queue is clear for this module.",
    "mobile.module.connection.no_scopes": "No granted scopes detected.",
    "mobile.module.connection.extra_scopes": "Least-privilege warning: extra scopes",
    "mobile.module.connection.missing_scopes": "Missing required scopes",
    "mobile.module.connection.baseline_ok": "Scope set matches least-privilege baseline.",
    "mobile.module.connection.connected_at": "Connected",
    "mobile.module.connection.updated_at": "Updated",
    "mobile.module.connection.expires_at": "Expires",
    "mobile.module.connection.scopes": "Scopes",
    "mobile.module.connection.none": "none",
    "mobile.module.action.accept": "Accept",
    "mobile.module.action.override": "Override",
    "mobile.module.action.connect": "Connect",
    "mobile.module.action.revoke": "Revoke",
    "mobile.module.action.run": "Run",
    "mobile.module.health.summary": "Summary",
    "mobile.module.health.window": "Window",
    "mobile.module.health.failures": "Open failures",
    "mobile.module.health.drop_rate": "Drop rate",
    "mobile.module.health.last_success": "Last success",
    "mobile.module.health.last_failure": "Last failure",
    "mobile.module.health.message": "Health update",
    "mobile.calendar.title": "Calendar",
    "mobile.calendar.subtitle": "Plan events linked to tasks, goals, and routines.",
    "mobile.calendar.quick_action.add_event": "Add event",
    "mobile.calendar.quick_action.force_sync": "Force sync",
    "mobile.settings.title": "Settings + more",
    "mobile.settings.subtitle": "Reach core mobile settings, sync tools, and the extra surfaces that do not belong in the main daily tab loop.",
    "mobile.settings.metric.language": "Language",
    "mobile.settings.metric.pending_sync_items": "Pending sync items",
    "mobile.settings.metric.auto_sync_on": "Auto sync on",
    "mobile.settings.metric.auto_sync_paused": "Auto sync paused",
    "mobile.settings.metric.manual_sync_available": "manual sync available",
    "mobile.settings.metric.lag": "lag",
    "mobile.settings.panel.core_settings": "Core settings",
    "mobile.settings.panel.core_settings_text": "Open the advanced settings modal for language selection, offline sync, notifications, and Copilot controls.",
    "mobile.settings.panel.open_advanced": "Open advanced settings",
    "mobile.settings.panel.module_access": "Module access",
    "mobile.settings.panel.module_access_text": "Routines and life areas are managed from the mobile habits and journal flows. These shortcuts make that easier to reach.",
    "mobile.settings.panel.additional_surfaces": "Additional surfaces",
    "mobile.settings.panel.additional_surfaces_text": "Keep the main tab bar focused on the daily loop while still exposing the non-core surfaces already available in the app.",
    "mobile.settings.route.habits_routines": "Habits + Routines",
    "mobile.settings.route.journal_life_areas": "Journal + Life Areas",
    "mobile.settings.route.goals_targets": "Goals + Targets",
    "mobile.settings.route.tasks_lists": "Tasks + Lists",
    "public.kicker": "Life management in one calm place",
    "public.nav.welcome": "Welcome",
    "public.nav.sign_in": "Sign in",
    "public.nav.register": "Register",
    "public.footer.runtime": "Web app: http://localhost:9001 | API: http://localhost:9000",
    "auth.title.login": "Sign in to your private workspace",
    "auth.title.register": "Create your Nest account",
    "auth.subtitle": "Sign in or create an account, then finish onboarding before entering your dashboard.",
    "auth.section.language": "Language",
    "auth.section.account": "Account access",
    "auth.section.status": "Status",
    "auth.section.error": "Something went wrong",
    "auth.switch_to_register": "Create account instead",
    "auth.switch_to_login": "Use existing account",
    "auth.field.name": "Name",
    "auth.field.email": "Email",
    "auth.field.password": "Password",
    "auth.field.password_confirm": "Confirm password",
    "auth.action.sign_in": "Sign in",
    "auth.action.signing_in": "Signing in...",
    "auth.action.create_account": "Create account",
    "auth.action.creating_account": "Creating account...",
    "auth.feedback.default": "Sign in to access your private workspace.",
    "auth.feedback.signed_in": "Signed in. Redirecting...",
    "auth.feedback.created": "Account created. Redirecting...",
    "auth.error.password_mismatch": "The password confirmation does not match.",
    "auth.error.login_invalid": "We couldn't sign you in. Check your email and password and try again.",
    "auth.error.login_generic": "We couldn't sign you in right now. Please try again in a moment.",
    "auth.error.register_generic": "We couldn't create your account right now. Please try again in a moment.",
    "auth.language.helper": "Choose the language for sign-in and onboarding. You can change it later in settings.",
    "onboarding.title": "Finish your account setup",
    "onboarding.subtitle": "Choose your display name and language before entering the dashboard.",
    "onboarding.required.display_name": "Required field",
    "onboarding.required.language": "Required field",
    "onboarding.apply_mode": "Applies",
    "onboarding.apply_mode.value": "Immediately",
    "onboarding.panel.title": "Account setup",
    "onboarding.field.display_name": "Display name",
    "onboarding.field.language": "Language",
    "onboarding.action.continue": "Continue",
    "onboarding.feedback.default": "Complete onboarding with your display name and language.",
    "onboarding.feedback.success": "Setup saved. Redirecting to your dashboard...",
    "onboarding.error.generic": "We couldn't save your setup right now. Please try again.",
    "dashboard.error.load": "We couldn't load the dashboard right now",
    "dashboard.greeting.morning": "Good morning",
    "dashboard.greeting.afternoon": "Good afternoon",
    "dashboard.greeting.evening": "Good evening",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "You've got this.",
    "dashboard.hero.title": "Today at a glance",
    "dashboard.hero.summary": "You're making steady progress.",
    "dashboard.hero.progress.showcase": "You're making steady progress.",
    "dashboard.hero.progress.live": "{tasks} completed tasks and {habits} active habits are already supporting the day.",
    "dashboard.metric.tasks_completed": "Tasks completed",
    "dashboard.metric.habits_active": "Active habits",
    "dashboard.metric.mindful_time": "Mindful time",
    "dashboard.metric.focus_score": "Focus score",
    "dashboard.timeline.type.routine": "Routine",
    "dashboard.timeline.type.habit": "Habit",
    "dashboard.timeline.type.focus_block": "Focus block",
    "dashboard.timeline.type.event": "Event",
    "dashboard.timeline.type.life_area": "Life area",
    "dashboard.timeline.type.recovery": "Recovery",
    "dashboard.timeline.now": "Now",
    "dashboard.timeline.morning_routine": "Morning routine",
    "dashboard.timeline.workout": "Workout",
    "dashboard.timeline.deep_work": "Deep work block",
    "dashboard.timeline.team_sync": "Team sync",
    "dashboard.timeline.product_workshop": "Prepare for product strategy workshop",
    "dashboard.timeline.family_time": "Family time",
    "dashboard.timeline.dinner_unwind": "Dinner and unwind",
    "dashboard.timeline.reflect_plan": "Reflect and plan",
    "dashboard.timeline.sleep": "Sleep",
    "dashboard.list.note.high_impact": "High impact",
    "dashboard.list.note.work": "Work",
    "dashboard.list.note.finance": "Finance",
    "dashboard.list.note.personal": "Personal",
    "dashboard.badge.today": "Today",
    "dashboard.badge.tomorrow": "Tomorrow",
    "dashboard.badge.open": "Open",
    "dashboard.habit.streak_days": "{count} days",
    "dashboard.reflection.fallback_title": "Evening reflection",
    "dashboard.reflection.fallback_body": "Today felt productive and meaningful. I made progress on what matters most and showed up for myself and others. Grateful for the small wins and the clarity that's coming.",
    "dashboard.reflection.prompt": "How was your day?",
    "dashboard.quick_add.task": "Task",
    "dashboard.quick_add.habit": "Habit",
    "dashboard.quick_add.event": "Event",
    "dashboard.quick_add.note": "Note",
    "dashboard.focus.kicker": "Now focus",
    "dashboard.focus.default_title": "Prepare for product strategy workshop",
    "dashboard.focus.showcase_detail": "This moves your project forward and aligns the team. A focused block now creates momentum for the week.",
    "dashboard.focus.live_detail": "This move is already alive in the day. Giving it clean attention now will create momentum for everything after it.",
    "dashboard.focus.cta": "Start focus session",
    "dashboard.focus.why": "Why this?",
    "dashboard.focus.meta.impact": "Impact",
    "dashboard.focus.meta.duration": "Duration",
    "dashboard.focus.meta.high_impact": "High impact",
    "dashboard.focus.meta.showcase_duration": "45 min",
    "dashboard.focus.meta.live_duration": "35 min",
    "dashboard.panel.now": "Now",
    "dashboard.panel.dayflow": "Morning / Now / Evening",
    "dashboard.panel.tasks": "Tasks",
    "dashboard.panel.habits": "Habits",
    "dashboard.panel.view_all": "View all",
    "dashboard.panel.view_all_tasks": "View all tasks",
    "dashboard.panel.add_task": "Add task",
    "dashboard.panel.view_full_calendar": "View full calendar",
    "dashboard.insight.title": "Insight of the day",
    "dashboard.insight.quote": "Clarity comes from slowing down long enough to hear what matters.",
    "dashboard.insight.cta": "Explore insights",
  },
  pl: {
    "app.kicker": "Nest LifeOS MVP",
    "app.nav.core_modules": "Glowne moduly",
    "app.nav.mobile_modules": "Moduly mobilne",
    "app.nav.dashboard": "Dashboard",
    "app.nav.planning": "Planowanie",
    "app.nav.habits": "Nawyki",
    "app.nav.routines": "Rutyny",
    "app.nav.calendar": "Kalendarz",
    "app.nav.journal": "Dziennik",
    "app.nav.life_areas": "Obszary zycia",
    "app.nav.insights": "Wnioski",
    "app.nav.assistant": "Asystent",
    "app.nav.settings": "Ustawienia",
    "app.nav.tasks": "Zadania",
    "app.nav.lists": "Listy",
    "app.nav.targets": "Targety",
    "app.nav.goals": "Cele",
    "app.quote.daily_intention": "Dobrze przezyte zycie buduje sie codziennie, intencjonalnie.",
    "app.account.welcome_back": "Milo cie znow widziec,",
    "app.utility.search_assistant": "Szukaj lub zapytaj Asystenta",
    "app.utility.notifications": "Powiadomienia",
    "app.action.sign_out": "Wyloguj sie",
    "app.action.signing_out": "Wylogowywanie...",
    "mobile.tab.tasks": "Zadania",
    "mobile.tab.habits": "Nawyki",
    "mobile.tab.goals": "Cele",
    "mobile.tab.journal": "Dziennik",
    "mobile.tab.calendar": "Kalendarz",
    "mobile.tab.insights": "Wnioski",
    "mobile.tab.settings": "Ustawienia",
    "mobile.module.state.loading": "Ladowanie",
    "mobile.module.state.empty": "Pusto",
    "mobile.module.state.error": "Blad",
    "mobile.module.state.success": "Gotowe",
    "mobile.module.panel.today": "Twoj dzien",
    "mobile.module.panel.quick_actions": "Szybkie akcje",
    "mobile.module.panel.live_snapshot": "Biezacy obraz",
    "mobile.module.panel.api_status": "Status klienta API",
    "mobile.module.panel.conflict_queue": "Kolejka konfliktow",
    "mobile.module.panel.connections": "Polaczenia",
    "mobile.module.panel.integration_health": "Zdrowie integracji",
    "mobile.module.badge.shared_client": "wspolny klient",
    "mobile.module.badge.clear": "czysto",
    "mobile.module.badge.open": "otwarte",
    "mobile.module.empty.conflicts.title": "Brak otwartych konfliktow",
    "mobile.module.empty.conflicts.detail": "Kolejka jest czysta dla tego modulu.",
    "mobile.module.connection.no_scopes": "Nie wykryto przyznanych zakresow.",
    "mobile.module.connection.extra_scopes": "Ostrzezenie least-privilege: dodatkowe zakresy",
    "mobile.module.connection.missing_scopes": "Brakuje wymaganych zakresow",
    "mobile.module.connection.baseline_ok": "Zestaw zakresow zgadza sie z minimalnym baseline.",
    "mobile.module.connection.connected_at": "Polaczono",
    "mobile.module.connection.updated_at": "Zaktualizowano",
    "mobile.module.connection.expires_at": "Wygasa",
    "mobile.module.connection.scopes": "Zakresy",
    "mobile.module.connection.none": "brak",
    "mobile.module.action.accept": "Akceptuj",
    "mobile.module.action.override": "Zastap",
    "mobile.module.action.connect": "Polacz",
    "mobile.module.action.revoke": "Cofnij",
    "mobile.module.action.run": "Uruchom",
    "mobile.module.health.summary": "Podsumowanie",
    "mobile.module.health.window": "Okno",
    "mobile.module.health.failures": "Otwarte bledy",
    "mobile.module.health.drop_rate": "Wspolczynnik odrzucen",
    "mobile.module.health.last_success": "Ostatni sukces",
    "mobile.module.health.last_failure": "Ostatnia porazka",
    "mobile.module.health.message": "Aktualizacja zdrowia",
    "mobile.calendar.title": "Kalendarz",
    "mobile.calendar.subtitle": "Planuj wydarzenia powiazane z zadaniami, celami i rutynami.",
    "mobile.calendar.quick_action.add_event": "Dodaj wydarzenie",
    "mobile.calendar.quick_action.force_sync": "Wymus synchronizacje",
    "mobile.settings.title": "Ustawienia i wiecej",
    "mobile.settings.subtitle": "Dotrzyj do glownych ustawien mobile, narzedzi synchronizacji i dodatkowych powierzchni, ktore nie naleza do glownej dziennej petli zakladek.",
    "mobile.settings.metric.language": "Jezyk",
    "mobile.settings.metric.pending_sync_items": "Oczekujace elementy sync",
    "mobile.settings.metric.auto_sync_on": "Auto sync wlaczony",
    "mobile.settings.metric.auto_sync_paused": "Auto sync wstrzymany",
    "mobile.settings.metric.manual_sync_available": "reczny sync dostepny",
    "mobile.settings.metric.lag": "opoznienie",
    "mobile.settings.panel.core_settings": "Glowne ustawienia",
    "mobile.settings.panel.core_settings_text": "Otworz zaawansowany modal ustawien dla wyboru jezyka, offline sync, powiadomien i sterowania Copilotem.",
    "mobile.settings.panel.open_advanced": "Otworz zaawansowane ustawienia",
    "mobile.settings.panel.module_access": "Dostep do modulow",
    "mobile.settings.panel.module_access_text": "Rutyny i obszary zycia sa zarzadzane z mobilnych przeplywow nawykow i dziennika. Te skroty ulatwiaja dotarcie tam.",
    "mobile.settings.panel.additional_surfaces": "Dodatkowe powierzchnie",
    "mobile.settings.panel.additional_surfaces_text": "Utrzymaj glowny pasek zakladek skupiony na dziennej petli, jednoczesnie udostepniajac powierzchnie niekrytyczne, ktore juz istnieja w aplikacji.",
    "mobile.settings.route.habits_routines": "Nawyki + Rutyny",
    "mobile.settings.route.journal_life_areas": "Dziennik + Obszary zycia",
    "mobile.settings.route.goals_targets": "Cele + Targety",
    "mobile.settings.route.tasks_lists": "Zadania + Listy",
    "public.kicker": "Zarzadzaj zyciem spokojnie, w jednym miejscu",
    "public.nav.welcome": "Start",
    "public.nav.sign_in": "Zaloguj sie",
    "public.nav.register": "Zarejestruj sie",
    "public.footer.runtime": "Web app: http://localhost:9001 | API: http://localhost:9000",
    "auth.title.login": "Zaloguj sie do swojego prywatnego workspace",
    "auth.title.register": "Utworz konto Nest",
    "auth.subtitle": "Zaloguj sie albo zaloz konto, a potem dokonczy onboarding przed wejsciem do dashboardu.",
    "auth.section.language": "Jezyk",
    "auth.section.account": "Dostep do konta",
    "auth.section.status": "Status",
    "auth.section.error": "Cos poszlo nie tak",
    "auth.switch_to_register": "Utworz nowe konto",
    "auth.switch_to_login": "Mam juz konto",
    "auth.field.name": "Imie",
    "auth.field.email": "Email",
    "auth.field.password": "Haslo",
    "auth.field.password_confirm": "Powtorz haslo",
    "auth.action.sign_in": "Zaloguj sie",
    "auth.action.signing_in": "Logowanie...",
    "auth.action.create_account": "Utworz konto",
    "auth.action.creating_account": "Tworzenie konta...",
    "auth.feedback.default": "Zaloguj sie, aby wejsc do swojego prywatnego workspace.",
    "auth.feedback.signed_in": "Zalogowano. Przekierowuje...",
    "auth.feedback.created": "Konto utworzone. Przekierowuje...",
    "auth.error.password_mismatch": "Potwierdzenie hasla nie zgadza sie.",
    "auth.error.login_invalid": "Nie udalo sie zalogowac. Sprawdz email i haslo, a potem sproboj ponownie.",
    "auth.error.login_generic": "Nie udalo sie teraz zalogowac. Sprobuj ponownie za chwile.",
    "auth.error.register_generic": "Nie udalo sie teraz utworzyc konta. Sprobuj ponownie za chwile.",
    "auth.language.helper": "Wybierz jezyk logowania i onboardingu. Pozniej zmienisz go w ustawieniach.",
    "onboarding.title": "Dokoncz konfiguracje konta",
    "onboarding.subtitle": "Ustaw nazwe wyswietlana i jezyk, zanim wejdziesz do dashboardu.",
    "onboarding.required.display_name": "Pole wymagane",
    "onboarding.required.language": "Pole wymagane",
    "onboarding.apply_mode": "Zastosowanie",
    "onboarding.apply_mode.value": "Od razu",
    "onboarding.panel.title": "Konfiguracja konta",
    "onboarding.field.display_name": "Nazwa wyswietlana",
    "onboarding.field.language": "Jezyk",
    "onboarding.action.continue": "Dalej",
    "onboarding.feedback.default": "Dokoncz onboarding, ustawiajac nazwe wyswietlana i jezyk.",
    "onboarding.feedback.success": "Ustawienia zapisane. Przekierowuje do dashboardu...",
    "onboarding.error.generic": "Nie udalo sie zapisac ustawien. Sprobuj ponownie.",
    "dashboard.error.load": "Nie udalo sie teraz zaladowac dashboardu",
    "dashboard.greeting.morning": "Dzien dobry",
    "dashboard.greeting.afternoon": "Dobre popoludnie",
    "dashboard.greeting.evening": "Dobry wieczor",
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Dasz rade.",
    "dashboard.hero.title": "Dzien w jednym spojrzeniu",
    "dashboard.hero.summary": "Robisz stabilny postep.",
    "dashboard.hero.progress.showcase": "Robisz stabilny postep.",
    "dashboard.hero.progress.live": "{tasks} ukonczonych zadan i {habits} aktywnych nawykow juz wspiera ten dzien.",
    "dashboard.metric.tasks_completed": "Ukonczone zadania",
    "dashboard.metric.habits_active": "Aktywne nawyki",
    "dashboard.metric.mindful_time": "Uważny czas",
    "dashboard.metric.focus_score": "Skupienie",
    "dashboard.timeline.type.routine": "Rutyna",
    "dashboard.timeline.type.habit": "Nawyk",
    "dashboard.timeline.type.focus_block": "Blok skupienia",
    "dashboard.timeline.type.event": "Wydarzenie",
    "dashboard.timeline.type.life_area": "Obszar zycia",
    "dashboard.timeline.type.recovery": "Regeneracja",
    "dashboard.timeline.now": "Teraz",
    "dashboard.timeline.morning_routine": "Poranna rutyna",
    "dashboard.timeline.workout": "Trening",
    "dashboard.timeline.deep_work": "Blok glebokiej pracy",
    "dashboard.timeline.team_sync": "Synchronizacja zespolu",
    "dashboard.timeline.product_workshop": "Przygotuj warsztat strategii produktu",
    "dashboard.timeline.family_time": "Czas z rodzina",
    "dashboard.timeline.dinner_unwind": "Kolacja i oddech",
    "dashboard.timeline.reflect_plan": "Refleksja i plan",
    "dashboard.timeline.sleep": "Sen",
    "dashboard.list.note.high_impact": "Wysoki wplyw",
    "dashboard.list.note.work": "Praca",
    "dashboard.list.note.finance": "Finanse",
    "dashboard.list.note.personal": "Prywatne",
    "dashboard.badge.today": "Dzis",
    "dashboard.badge.tomorrow": "Jutro",
    "dashboard.badge.open": "Otwarte",
    "dashboard.habit.streak_days": "{count} dni",
    "dashboard.reflection.fallback_title": "Wieczorna refleksja",
    "dashboard.reflection.fallback_body": "To byl produktywny i sensowny dzien. Posunelam to, co najwazniejsze, i pokazalam sie dla siebie oraz innych. Doceniam male wygrane i klarownosc, ktora przychodzi.",
    "dashboard.reflection.prompt": "Jak minal twoj dzien?",
    "dashboard.quick_add.task": "Zadanie",
    "dashboard.quick_add.habit": "Nawyk",
    "dashboard.quick_add.event": "Wydarzenie",
    "dashboard.quick_add.note": "Notatka",
    "dashboard.focus.kicker": "Priorytet teraz",
    "dashboard.focus.default_title": "Przygotuj warsztat strategii produktu",
    "dashboard.focus.showcase_detail": "To popycha projekt do przodu i ustawia zespol. Skupiony blok teraz zbuduje impet na caly tydzien.",
    "dashboard.focus.live_detail": "Ten ruch juz zyje w planie dnia. Czysta uwaga teraz zbuduje impet dla wszystkiego, co dalej.",
    "dashboard.focus.cta": "Zacznij sesje skupienia",
    "dashboard.focus.why": "Dlaczego to?",
    "dashboard.focus.meta.impact": "Wplyw",
    "dashboard.focus.meta.duration": "Czas",
    "dashboard.focus.meta.high_impact": "Wysoki wplyw",
    "dashboard.focus.meta.showcase_duration": "45 min",
    "dashboard.focus.meta.live_duration": "35 min",
    "dashboard.panel.now": "Teraz",
    "dashboard.panel.dayflow": "Rano / Teraz / Wieczor",
    "dashboard.panel.tasks": "Zadania",
    "dashboard.panel.habits": "Nawyki",
    "dashboard.panel.view_all": "Zobacz wszystkie",
    "dashboard.panel.view_all_tasks": "Zobacz wszystkie zadania",
    "dashboard.panel.add_task": "Dodaj zadanie",
    "dashboard.panel.view_full_calendar": "Zobacz pelny kalendarz",
    "dashboard.insight.title": "Wniosek dnia",
    "dashboard.insight.quote": "Klarownosc przychodzi, kiedy zwolnisz na tyle, by uslyszec to, co ma znaczenie.",
    "dashboard.insight.cta": "Otworz wnioski",
  },
};

export function resolveLanguage(value) {
  if (typeof value === "string" && SUPPORTED_LANGUAGES.includes(value)) {
    return value;
  }

  return "en";
}

export function resolveLocale(language, override) {
  if (typeof override === "string" && override.length > 0) {
    return override;
  }

  const safeLanguage = resolveLanguage(language);
  return DEFAULT_LOCALES[safeLanguage];
}

export function translate(key, language, fallback = key) {
  const safeLanguage = resolveLanguage(language);
  return DICTIONARY[safeLanguage]?.[key] ?? DICTIONARY.en?.[key] ?? fallback;
}

export function formatLocalizedDateTime(value, language, localeOverride) {
  const locale = resolveLocale(language, localeOverride);
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "";
  }

  return new Intl.DateTimeFormat(locale, {
    dateStyle: "short",
    timeStyle: "short",
  }).format(date);
}
