<?php

return [
    'retention_days' => (int) env('ANALYTICS_RETENTION_DAYS', 180),
    'max_batch_size' => (int) env('ANALYTICS_INGEST_MAX_BATCH_SIZE', 100),
    'allowed_platforms' => ['web', 'mobile', 'api', 'system'],
    'allowed_modules' => ['tasks', 'habits', 'goals', 'journal', 'calendar', 'integrations'],
    'allowed_event_names' => [
        'tasks.list.created',
        'tasks.list.updated',
        'tasks.task.created',
        'tasks.task.completed',
        'tasks.task.reopened',
        'tasks.task.deleted',
        'habits.habit.created',
        'habits.habit.logged',
        'habits.habit.paused',
        'habits.routine.created',
        'habits.routine.executed',
        'goals.goal.created',
        'goals.goal.status_changed',
        'goals.target.created',
        'goals.target.progress_updated',
        'journal.entry.created',
        'journal.entry.updated',
        'journal.entry.deleted',
        'journal.life_area.weight_changed',
        'calendar.event.created',
        'calendar.event.updated',
        'calendar.event.deleted',
        'calendar.event.linked_entity_changed',
        'integrations.connection.connected',
        'integrations.connection.revoked',
        'integrations.sync.started',
        'integrations.sync.completed',
        'integrations.sync.failed',
        'integrations.conflict.detected',
        'integrations.conflict.resolved',
    ],
];
