<?php

return [
    'retention_policies' => [
        [
            'table' => 'analytics_events',
            'timestamp_column' => 'occurred_at',
            'retention_days' => 180,
        ],
        [
            'table' => 'integration_sync_audits',
            'timestamp_column' => 'occurred_at',
            'retention_days' => 90,
        ],
        [
            'table' => 'integration_sync_failures',
            'timestamp_column' => 'failed_at',
            'retention_days' => 90,
        ],
        [
            'table' => 'integration_sync_conflicts',
            'timestamp_column' => 'created_at',
            'retention_days' => 90,
        ],
        [
            'table' => 'integration_event_ingestions',
            'timestamp_column' => 'received_at',
            'retention_days' => 30,
        ],
        [
            'table' => 'integration_marketplace_audits',
            'timestamp_column' => 'occurred_at',
            'retention_days' => 180,
        ],
        [
            'table' => 'integration_marketplace_installs',
            'timestamp_column' => 'updated_at',
            'retention_days' => 3650,
        ],
        [
            'table' => 'billing_self_serve_sessions',
            'timestamp_column' => 'created_at',
            'retention_days' => 180,
        ],
        [
            'table' => 'billing_dunning_attempts',
            'timestamp_column' => 'processed_at',
            'retention_days' => 365,
        ],
        [
            'table' => 'mobile_push_deliveries',
            'timestamp_column' => 'delivered_at',
            'retention_days' => 30,
        ],
        [
            'table' => 'notification_channel_deliveries',
            'timestamp_column' => 'created_at',
            'retention_days' => 90,
        ],
        [
            'table' => 'in_app_notifications',
            'timestamp_column' => 'created_at',
            'retention_days' => 180,
        ],
        [
            'table' => 'ai_action_proposals',
            'timestamp_column' => 'created_at',
            'retention_days' => 180,
        ],
        [
            'table' => 'ai_briefings',
            'timestamp_column' => 'generated_at',
            'retention_days' => 180,
        ],
        [
            'table' => 'ai_briefing_preferences',
            'timestamp_column' => 'updated_at',
            'retention_days' => 3650,
        ],
        [
            'table' => 'automation_runs',
            'timestamp_column' => 'created_at',
            'retention_days' => 180,
        ],
    ],
    'deletion_tables' => [
        'ai_briefings',
        'ai_briefing_preferences',
        'ai_action_proposals',
        'ai_recommendation_feedback',
        'automation_runs',
        'automation_rules',
        'analytics_events',
        'mobile_push_deliveries',
        'mobile_push_devices',
        'notification_channel_deliveries',
        'notification_preferences',
        'in_app_notifications',
        'integration_sync_conflicts',
        'integration_event_ingestions',
        'integration_marketplace_audits',
        'integration_marketplace_installs',
        'billing_dunning_attempts',
        'billing_self_serve_sessions',
        'tenant_billing_events',
        'tenant_subscriptions',
        'integration_sync_audits',
        'integration_sync_failures',
        'sync_mappings',
        'calendar_events',
        'journal_entry_life_area',
        'journal_entries',
        'targets',
        'goals',
        'routine_steps',
        'routines',
        'habit_logs',
        'habits',
        'tasks',
        'task_lists',
        'projects',
        'life_areas',
        'integration_credentials',
        'users',
        'tenants',
    ],
];
